language: cpp
compiler: g++
sudo: false

addons:
  apt:
    packages:
    - cmake

script:
- if [ "$CXX" == "clang++" ]; then export CXX="clang++" && bii cpp:build; fi
- if [ "$CXX" == "g++" ];     then export CXX="g++"     && bii cpp:build; fi