addons:
    apt:
        sources:
#            - llvm-toolchain-precise
             - ubuntu-toolchain-r-test
        packages:
#            - clang-3.7
             - g++-5
#            - gcc-5

#sudo: required
#dist: trusty
#sudo: false

language: cpp


    
install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - mkdir build
  - cd ./build
  - cmake ..
  - make
  - ctest