language: cpp
compiler: g++
sudo: false

compiler: gcc
addons:
apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['g++-4.9', 'cmake']

env: COMPILER=g++-4.9
    
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-i386.tar.gz
      && tar -xzf cmake-3.3.2-Linux-i386.tar.gz
      && cp -fR cmake-3.3.2-Linux-i386/* /usr
      && export CXX="g++-4.9"
      && export CC="gcc-4.9"
      ;    
    fi   
    



script:
  - mkdir build
  - cd ./build
  - cmake ..
  - make
  - ctest