/*
 * propertie.hpp
 *
 *  Created on: May 14, 2016
 *      Author: dan
 */

#ifndef NINJA_WOOKIE_BACNET_TYPE_PROPERTIE_HPP_
#define NINJA_WOOKIE_BACNET_TYPE_PROPERTIE_HPP_

#include <bacnet/type/detail/properties_impl.hpp>

namespace bacnet { namespace type { namespace property {
/*
WOOKIE_DEFINE_BACNET_PROPERTIES(
    ((acked_transition,     0,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_NORMAL_PROPERTY   ))
    ((ack_required,         1,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_NORMAL_PROPERTY   ))
    ((action,               2,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_NORMAL_PROPERTY   ))
    ((action_text,          3,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_NORMAL_PROPERTY   ))
    ((active_vt_sessions,   4,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_NORMAL_PROPERTY   ))
    ((alarm_value,          5,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_NORMAL_PROPERTY   ))
    ((alarm_values,         6,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_NORMAL_PROPERTY   ))
    ((all,                  7,    WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
) */


WOOKIE_DEFINE_BACNET_PROPERTIES(
    ((  acked_transitions,                     0  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  ack_required,                          1  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  action,                                2  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  action_text,                           3  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  active_text,                           4  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  active_vt_sessions,                    5  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  alarm_value,                           6  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  alarm_values,                          7  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  all,                                   8  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  all_writes_successful,                 9  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  apdu_segment_timeout,                 10  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  apdu_timeout,                         11  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  application_software_version,         12  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  archive,                              13  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  bias,                                 14  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  change_of_state_count,                15  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  change_of_state_time,                 16  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  notification_class,                   17  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    /*                                        18        ,deleted   */
    ((  controlled_variable_reference,        19  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  controlled_variable_units,            20  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  controlled_variable_value,            21  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  cov_increment,                        22  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  date_list,                            23  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  daylight_savings_status,              24  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  deadband,                             25  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  derivative_constant,                  26  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  derivative_constant_units,            27  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  description,                          28  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  description_of_halt,                  29  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  device_address_binding,               30  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  device_type,                          31  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  effective_period,                     32  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  elapsed_active_time,                  33  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  error_limit,                          34  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_enable,                         35  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_state,                          36  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_type,                           37  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  exception_schedule,                   38  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  fault_values,                         39  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  feedback_value,                       40  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  file_access_method,                   41  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  file_size,                            42  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  file_type,                            43  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  firmware_revision,                    44  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  high_limit,                           45  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  inactive_text,                        46  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  in_process,                           47  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  instance_of,                          48  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  integral_constant,                    49  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  integral_constant_units,              50  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
   /*  issue_confirmed_notifications,      51        ,  removed in version 1 revision 4     */
    ((  limit_enable,                         52  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  list_of_group_members,                53  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  list_of_object_property_references,   54  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    /*  value 55 is unassigned,*/
    ((  local_date,                           56  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  local_time,                           57  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  location,                             58  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  low_limit,                            59  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  manipulated_variable_reference,       60  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  maximum_output,                       61  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  max_apdu_length_accepted,             62  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  max_info_frames,                      63  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  max_master,                           64  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  max_pres_value,                       65  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  minimum_off_time,                     66  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  minimum_on_time,                      67  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  minimum_output,                       68  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  min_pres_value,                       69  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  model_name,                           70  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  modification_date,                    71  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  notify_type,                          72  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  number_of_apdu_retries,               73  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  number_of_states,                     74  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  object_identifier,                    75  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  object_list,                          76  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  object_name,                          77  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  object_property_reference,            78  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  object_type,                          79  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  optional,                             80  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  out_of_service,                       81  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  output_units,                         82  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_parameters,                     83  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  polarity,                             84  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  present,                              85  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  priority,                             86  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  priority_array,                       87  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  priority_for_writing,                 88  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  process_identifier,                   89  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  program_change,                       90  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  program_location,                     91  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  program_state,                        92  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  proportional_constant,                93  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  proportional_constant_units,          94  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    /*  protocol_conformance_class,           95        removed in version 1 revision 2. */
    ((  protocol_object_types_supported,      96  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  protocol_services_supported,          97  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  protocol_version,                     98  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  read_only,                            99  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  reason_for_halt,                      100 ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    /*  recipient,                            101        removed in version 1 revision 4.   */
 /*   ((  recipient_list,                       102  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  reliability                           103  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  relinquish_default,                   104  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  required,                             105  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  resolution,                           106  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  segmentation_supported,               107  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  setpoint,                             108  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  setpoint_reference,                   109  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  state_text,                           110  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  status_flags,                         111  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  system_status,                        112  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  time_delay,                           113  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  time_of_active_time_reset,            114  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  time_of_state_count_reset,            115  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  time_synchronization_recipients,      116  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  units,                                117  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  update_interval,                      118  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  utc_offset,                           119  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  vendor_identifier,                    120  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  vendor_name,                          121  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  vt_classes_supported,                 122  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  weekly_schedule,                      123  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  attempted_samples,                    124  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  average_value,                        125  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  buffer_size,                          126  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  client_cov_increment,                 127  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  cov_resubscription_interval,          128  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
  */  /*  current_notify_time,                  129        removed in version 1 revision 3.*/
 /*   ((  event_time_stamps,                    130  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  log_buffer,                           131  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  log_device_object_property,           132  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
*/ /*    ((  enable,                               133        ,"log_enable was renamed to enable in version 1 revision 5  ,   )) */
 /*   ((  log_interval,                         134  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  maximum_value,                        135  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  minimum_value,                        136  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  notification_threshold,               137  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
  */  /*((  previous_notify_time,                 138        removed in version 1 revision 3.  */
 /*   ((  protocol_revision,                    139  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  records_since_notification,           140  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  record_count,                         141  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  start_time,                           142  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  stop_time,                            143  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  stop_when_full,                       144  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  total_record_count,                   145  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  valid_samples,                        146  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  window_interval,                      147  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  window_samples,                       148  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  maximum_value_timestamp,              149  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  minimum_value_timestamp,              150  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  variance_value,                       151  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  active_cov_subscriptions,             152  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  backup_failure_timeout,               153  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  configuration_files,                  154  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  database_revision,                    155  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  direct_reading,                       156  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_restore_time,                    157  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  maintenance_required,                 158  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  member_of,                            159  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  mode,                                 160  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  operation_expected,                   161  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  setting,                              162  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  silenced,                             163  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  tracking_value,                       164  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  zone_members,                         165  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  life_safety_alarm_values,             166  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  max_segments_accepted,                167  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  profile_name,                         168  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  auto_slave_discovery,                 169  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  manual_slave_address_binding,         170  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  slave_address_binding,                171  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  slave_proxy_enable,                   172  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_notify_record,                   173  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  schedule_default,                     174  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  accepted_modes,                       175  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  adjust_value,                         176  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  count,                                177  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  count_before_change,                  178  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  count_change_time,                    179  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  cov_period,                           180  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  input_reference,                      181  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  limit_monitoring_interval,            182  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  logging_object,                       183  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  logging_record,                       184  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  prescale,                             185  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  pulse_rate,                           186  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  scale,                                187  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  scale_factor,                         188  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  update_time,                          189  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  value_before_change,                  190  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  value_set,                            191  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  value_change_time,                    192  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  align_intervals,                      193  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
  */  /*  value 194  unassigned   */
 /*   ((  interval_offset,                      195  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_restart_reason,                  196  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  logging_type,                         197  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
  */  /*   198_201 unassigned   */
 /*   ((  restart_notification_recipients,      202  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  time_of_device_restart,               203  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  time_synchronization_interval,        204  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  trigger,                              205  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  Utc_time_synchronization_recipients,  206  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  node_subtype,                         207  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  node_type,                            208  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  structured_object_list,               209  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  subordinate_annotations,              210  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  subordinate_list,                     211  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  actual_shed_level,                    212  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  duty_window,                          213  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  expected_shed_level,                  214  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  full_duty_baseline,                   215  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
 */   /*   values 216_217 are unassigned */
  /*  ((  requested_shed_level,                 218  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  shed_duration,                        219  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  shed_level_descriptions,              220  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  shed_levels,                          221  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  state_description,                    222  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
   */ /*  values 223_225 are unassigned  */
  /*  ((  door_alarm_state,                     226  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  door_extended_pulse_time,             227  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  door_members,                         228  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  door_open_too_long_time,              229  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  door_pulse_time,                      230  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  door_status,                          231  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  door_unlock_delay_time,               232  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  lock_status,                          233  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  masked_alarm_values,                  234  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  secured_status,                       235  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
   */ /*  Values 236-243 unassigned   */
 /*   ((  absentee_limit,                       244  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_alarm_events,                  245  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_doors,                         246  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_event,                         247  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_event_authentication_factor,   248  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_event_credential,              249  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_event_time,                    250  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_transaction_events,            251  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  accompaniment,                        252  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  accompaniment_time,                   253  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  activation_time,                      254  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  active_authentication_policy,         255  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  assigned_access_rights,               256  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  authentication_factors,               257  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  authentication_policy_list,           258  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  authentication_policy_names,          259  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  authentication_status,                260  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  authorization_mode,                   261  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  belongs_to,                           262  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  credential_disable,                   263  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  credential_status,                    264  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  credentials,                          265  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  credentials_in_zone,                  266  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  days_remaining,                       267  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  entry_points,                         268  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  exit_points,                          269  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  expiry_time,                          270  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  extended_time_enable,                 271  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  failed_attempt_events,                272  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  failed_attempts,                      273  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  failed_attempts_time,                 274  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_access_event,                    275  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_access_point,                    276  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_credential_added,                277  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_credential_added_time,           278  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_credential_removed,              279  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_credential_removed_time,         280  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_use_time,                        281  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  lockout,                              282  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  lockout_relinquish_time,              283  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
  */  /*  master_exemption,                     284        removed in version 1 revision 13  */
/*    ((  max_failed_attempts,                  285  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  members,                              286  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  muster_point,                         287  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  negative_access_rules,                288  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  number_of_authentication_policies,    289  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  occupancy_count,                      290  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  occupancy_count_adjust,               291  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  occupancy_count_enable,               292  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
   */ /*  occupancy_exemption,                  293         removed in version 1 revision 13  */
  /*  ((  occupancy_lower_limit,                294  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  occupancy_lower_limit_enforced,       295  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  occupancy_state,                      296  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  occupancy_upper_limit,                297  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  occupancy_upper_limit_enforced,       298  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
  */  /*  passback_exemption,                   299        removed in version 1 revision 13   */
  /*  ((  passback_mode,                        300  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  passback_timeout,                     301  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  positive_access_rules,                302  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  reason_for_disable,                   303  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  supported_formats,                    304  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  supported_format_classes,             305  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  threat_authority,                     306  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  threat_level,                         307  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  trace_flag,                           308  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  transaction_notification_class,       309  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  user_external_identifier,             310  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  user_information_reference,           311  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
   */ /*  Values 312_316 unassigned */
/*    ((  user_name,                            317  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  user_type,                            318  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  uses_remaining,                       319  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  zone_from,                            320  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  zone_to,                              321  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  access_event_tag,                     322  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  global_identifier,                    323  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
 */   /*  Values 324_325 unassigned*/
/*    ((  verification_time,                    326  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  base_device_security_policy,          327  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  distribution_key_revision,            328  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  do_not_hide,                          329  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  key_sets,                             330  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_key_server,                      331  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  network_access_security_policies,     332  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  packet_reorder_time,                  333  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  security_pdu_timeout,                 334  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  security_time_window,                 335  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  supported_security_algorithms,        336  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  update_key_set_timeout,               337  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  backup_and_restore_state,             338  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  backup_preparation_time,              339  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  restore_completion_time,              340  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  restore_preparation_time,             341  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  bit_mask,                             342  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  bit_text,                             343  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  is_utc,                               344  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  group_members,                        345  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  group_member_names,                   346  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  member_status_flags,                  347  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  requested_update_interval,            348  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  covu_period,                          349  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  covu_recipients,                      350  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_message_texts,                  351  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_message_texts_config,           352  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_detection_enable,               353  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_algorithm_inhibit,              354  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  event_algorithm_inhibit_ref,          355  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  time_delay_normal,                    356  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  reliability_evaluation_inhibit,       357  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  fault_parameters,                     358  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  fault_type,                           359  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  local_forwarding_only,                360  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  process_identifier_filter,            361  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  subscribed_recipients,                362  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  port_filter,                          363  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  authorization_exemptions,             364  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  allow_group_delay_inhibit,            365  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  channel_number,                       366  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  control_groups,                       367  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  execution_delay,                      368  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  last_priority,                        369  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  write_status,                         370  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  property_list,                        371  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  serial_number,                        372  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  blink_warn_enable,                    373  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  default_fade_time,                    374  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  default_ramp_rate,                    375  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  default_step_increment,               376  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  egress_time,                          377  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  in_progress,                          378  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  instantaneous_power,                  379  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  lighting_command,                     380  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  lighting_command_default_priority,    381  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  max_actual_value,                     382  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  min_actual_value,                     383  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  power,                                384  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  transition,                           385  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  ))
    ((  egress_active,                        386  ,  WOOKIE_BACNET_IS_STANDARD_PROPERTY, WOOKIE_BACNET_IS_SPECIAL_PROPERTY  )) */
)


}}}

void test() {

  using namespace bacnet::type;

  auto id                   = property::ack_required::value;
  auto id_trait             = property::id<                 property::ack_required>::value;
  auto name                 = property::name<               property::all>::value;
  auto is_standard_proprty  = property::is_standard_property<property::all>::value;
  auto is_speciial_property = property::is_special_operation_property<property::all>::value;

}



#endif /* NINJA_WOOKIE_BACNET_TYPE_PROPERTIE_HPP_ */
